import { Snapshot, FAQItem, Testimonial, Stat } from "./types";

export const SNAPSHOTS: Snapshot[] = [
  {
    id: "1",
    name: "SaaS Agency Snapshot",
    slug: "saas-agency",
    industry: "SaaS Agency",
    category: "Agency",
    description: "Complete SaaS agency setup with white-label dashboards, onboarding flows, and churn-prevention automations.",
    longDescription: "Launch your SaaS agency with everything pre-built. This snapshot includes client onboarding workflows, automated billing reminders, usage-based nurture sequences, churn prevention triggers, and a fully branded client portal. Perfect for agencies reselling GHL as a white-label SaaS platform.",
    price: 197,
    features: ["White-label client portal", "Automated onboarding sequence", "Churn prevention workflows", "Usage tracking pipelines", "Billing & invoice automations"],
    includes: ["5 Pipelines", "18 Automations", "3 Funnels", "12 Email Templates", "4 Workflows"],
    thumbnailGradient: ["#6366F1", "#8B5CF6"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "2",
    name: "Marketing Agency Snapshot",
    slug: "marketing-agency",
    industry: "Marketing Agency",
    category: "Agency",
    description: "Full-service marketing agency CRM with lead management, reporting dashboards, and client communication flows.",
    longDescription: "Everything a digital marketing agency needs to manage clients and leads. Includes prospect intake forms, proposal pipelines, project management workflows, automated reporting triggers, and client communication sequences. Built for agencies handling SEO, PPC, social media, and web design clients.",
    price: 197,
    features: ["Client intake & proposal pipeline", "Automated reporting workflows", "Multi-channel follow-up sequences", "Project status tracking", "Review request automations"],
    includes: ["6 Pipelines", "22 Automations", "4 Funnels", "15 Email Templates", "5 Workflows"],
    thumbnailGradient: ["#3B82F6", "#6366F1"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "3",
    name: "Solar Snapshot",
    slug: "solar",
    industry: "Solar",
    category: "Home Services",
    description: "Solar company CRM with appointment booking, proposal tracking, and installation pipeline management.",
    longDescription: "Purpose-built for solar installation companies. Manages the entire customer journey from initial inquiry to installation completion. Includes roof assessment scheduling, proposal generation workflows, financing application tracking, permit status pipelines, and post-install review requests.",
    price: 147,
    features: ["Roof assessment scheduling", "Proposal & financing pipeline", "Permit tracking workflows", "Installation scheduling", "Post-install follow-up"],
    includes: ["4 Pipelines", "14 Automations", "2 Funnels", "10 Email Templates", "3 Workflows"],
    thumbnailGradient: ["#F59E0B", "#EF4444"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "4",
    name: "Plumbing Snapshot",
    slug: "plumbing",
    industry: "Plumbing",
    category: "Home Services",
    description: "Plumbing business CRM with emergency dispatch, estimate tracking, and seasonal maintenance campaigns.",
    longDescription: "Built for plumbing companies of all sizes. Handles emergency service requests, estimate approvals, job scheduling, and follow-up sequences. Includes seasonal maintenance campaign templates for water heater flushes, pipe inspections, and winterization services.",
    price: 97,
    features: ["Emergency dispatch workflows", "Estimate approval tracking", "Job scheduling pipeline", "Seasonal campaign templates", "Review generation system"],
    includes: ["3 Pipelines", "12 Automations", "2 Funnels", "8 Email Templates", "3 Workflows"],
    thumbnailGradient: ["#3B82F6", "#0EA5E9"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "5",
    name: "Pest Control Snapshot",
    slug: "pest-control",
    industry: "Pest Control",
    category: "Home Services",
    description: "Pest control CRM with recurring service management, seasonal campaigns, and automated appointment reminders.",
    longDescription: "Designed for pest control operators. Manages one-time treatments and recurring service plans. Includes seasonal pest alert campaigns, appointment reminders, service renewal automations, and a referral program workflow. Perfect for companies offering termite, rodent, and general pest services.",
    price: 97,
    features: ["Recurring service management", "Seasonal pest alert campaigns", "Appointment reminder system", "Service renewal automations", "Referral program workflow"],
    includes: ["3 Pipelines", "10 Automations", "2 Funnels", "8 Email Templates", "3 Workflows"],
    thumbnailGradient: ["#EF4444", "#F97316"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "6",
    name: "HVAC Snapshot",
    slug: "hvac",
    industry: "HVAC",
    category: "Home Services",
    description: "HVAC company CRM with maintenance plan management, seasonal promotions, and emergency service workflows.",
    longDescription: "Complete HVAC business management system. Handles AC and heating service calls, maintenance plan enrollments, seasonal tune-up campaigns, and equipment replacement pipelines. Includes energy efficiency consultation booking and financing application workflows.",
    price: 127,
    features: ["Maintenance plan management", "Seasonal tune-up campaigns", "Emergency service dispatch", "Equipment replacement pipeline", "Financing application flow"],
    includes: ["4 Pipelines", "14 Automations", "2 Funnels", "10 Email Templates", "4 Workflows"],
    thumbnailGradient: ["#0EA5E9", "#6366F1"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "7",
    name: "Roofing Snapshot",
    slug: "roofing",
    industry: "Roofing",
    category: "Home Services",
    description: "Roofing contractor CRM with storm damage workflows, insurance claim tracking, and inspection scheduling.",
    longDescription: "Built for roofing contractors handling residential and commercial projects. Includes storm damage lead capture, insurance claim tracking pipelines, free inspection scheduling, estimate approval workflows, and post-project review requests. Perfect for both storm chasers and established roofing companies.",
    price: 127,
    features: ["Storm damage lead capture", "Insurance claim tracking", "Inspection scheduling", "Estimate approval pipeline", "Post-project review requests"],
    includes: ["4 Pipelines", "12 Automations", "3 Funnels", "9 Email Templates", "3 Workflows"],
    thumbnailGradient: ["#DC2626", "#9333EA"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "8",
    name: "Landscaping Snapshot",
    slug: "landscaping",
    industry: "Landscaping",
    category: "Home Services",
    description: "Landscaping business CRM with seasonal service management, estimate workflows, and maintenance plan tracking.",
    longDescription: "Everything a landscaping company needs. Manages weekly maintenance clients, one-time project estimates, seasonal service upsells, and crew scheduling. Includes spring cleanup campaigns, fall leaf removal promotions, and holiday lighting service workflows.",
    price: 97,
    features: ["Seasonal service campaigns", "Estimate & proposal pipeline", "Weekly maintenance tracking", "Crew scheduling workflows", "Upsell automation sequences"],
    includes: ["3 Pipelines", "11 Automations", "2 Funnels", "8 Email Templates", "3 Workflows"],
    thumbnailGradient: ["#22C55E", "#10B981"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "9",
    name: "Electrician Snapshot",
    slug: "electrician",
    industry: "Electrician",
    category: "Home Services",
    description: "Electrical contractor CRM with service call management, estimate tracking, and safety inspection workflows.",
    longDescription: "Designed for electrical contractors. Handles residential and commercial service calls, panel upgrade consultations, EV charger installation inquiries, and safety inspection scheduling. Includes emergency electrical service dispatch and generator installation pipelines.",
    price: 97,
    features: ["Service call management", "Panel upgrade pipeline", "EV charger inquiry flow", "Safety inspection scheduling", "Emergency dispatch system"],
    includes: ["3 Pipelines", "10 Automations", "2 Funnels", "8 Email Templates", "3 Workflows"],
    thumbnailGradient: ["#F59E0B", "#EAB308"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "10",
    name: "Restaurant Snapshot",
    slug: "restaurant",
    industry: "Restaurant",
    category: "Local Business",
    description: "Restaurant CRM with reservation management, loyalty programs, and event booking workflows.",
    longDescription: "Complete restaurant management system. Includes online reservation booking, birthday and anniversary automations, loyalty reward tracking, catering inquiry pipelines, and event space booking workflows. Perfect for casual dining, fine dining, and fast-casual restaurants.",
    price: 97,
    features: ["Reservation management", "Birthday & anniversary automations", "Loyalty reward tracking", "Catering inquiry pipeline", "Event booking workflows"],
    includes: ["3 Pipelines", "12 Automations", "2 Funnels", "10 Email Templates", "3 Workflows"],
    thumbnailGradient: ["#EF4444", "#F97316"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "11",
    name: "Med Spa Snapshot",
    slug: "med-spa",
    industry: "Med Spa",
    category: "Health & Wellness",
    description: "Med spa CRM with treatment booking, membership management, and before/after follow-up sequences.",
    longDescription: "Purpose-built for medical spas and aesthetic clinics. Manages treatment consultations, membership packages, pre and post-treatment communications, and rebooking sequences. Includes Botox and filler reminder campaigns, seasonal promotion workflows, and VIP client nurture sequences.",
    price: 147,
    features: ["Treatment consultation booking", "Membership management", "Pre/post-treatment sequences", "Rebooking reminder campaigns", "VIP client nurture"],
    includes: ["4 Pipelines", "16 Automations", "3 Funnels", "12 Email Templates", "4 Workflows"],
    thumbnailGradient: ["#EC4899", "#A855F7"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "12",
    name: "Fitness Snapshot",
    slug: "fitness",
    industry: "Fitness",
    category: "Health & Wellness",
    description: "Gym and fitness studio CRM with membership sales, class booking, and retention automations.",
    longDescription: "Built for gyms, CrossFit boxes, yoga studios, and personal trainers. Includes free trial workflows, membership sales pipelines, class booking management, member check-in tracking, and cancellation prevention sequences. Perfect for both boutique studios and larger fitness facilities.",
    price: 127,
    features: ["Free trial to member pipeline", "Class booking management", "Member retention automations", "Cancellation prevention", "Referral reward program"],
    includes: ["4 Pipelines", "14 Automations", "3 Funnels", "10 Email Templates", "4 Workflows"],
    thumbnailGradient: ["#8B5CF6", "#EC4899"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "13",
    name: "Life Insurance Snapshot",
    slug: "life-insurance",
    industry: "Life Insurance",
    category: "Insurance & Finance",
    description: "Life insurance agency CRM with lead nurturing, policy tracking, and annual review automations.",
    longDescription: "Designed for independent life insurance agents and agencies. Manages lead intake, needs analysis scheduling, policy application tracking, and annual review reminders. Includes term life conversion campaigns, beneficiary update workflows, and cross-sell sequences for disability and long-term care.",
    price: 147,
    features: ["Lead nurture sequences", "Policy application pipeline", "Annual review reminders", "Term conversion campaigns", "Cross-sell automations"],
    includes: ["4 Pipelines", "14 Automations", "2 Funnels", "10 Email Templates", "4 Workflows"],
    thumbnailGradient: ["#0EA5E9", "#3B82F6"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "14",
    name: "Real Estate Snapshot",
    slug: "real-estate",
    industry: "Real Estate",
    category: "Professional Services",
    description: "Real estate agent CRM with buyer/seller pipelines, showing scheduling, and drip campaigns.",
    longDescription: "Complete real estate CRM for agents and brokerages. Includes buyer and seller pipelines, showing request management, offer tracking, closing coordination workflows, and long-term nurture drip campaigns. Features market update automations and anniversary follow-ups for past clients.",
    price: 147,
    features: ["Buyer & seller pipelines", "Showing request management", "Offer tracking workflows", "Closing coordination", "Anniversary follow-ups"],
    includes: ["5 Pipelines", "16 Automations", "3 Funnels", "12 Email Templates", "4 Workflows"],
    thumbnailGradient: ["#10B981", "#059669"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "15",
    name: "Home Improvement Snapshot",
    slug: "home-improvement",
    industry: "Home Improvement",
    category: "Home Services",
    description: "Home improvement contractor CRM with project estimation, scheduling, and warranty tracking.",
    longDescription: "Built for general contractors and home improvement companies. Handles kitchen and bathroom remodel inquiries, project estimation workflows, material ordering coordination, and warranty registration. Includes seasonal promotion campaigns for windows, siding, and deck projects.",
    price: 97,
    features: ["Project estimation pipeline", "Material coordination workflows", "Warranty registration", "Seasonal promotion campaigns", "Post-project follow-up"],
    includes: ["3 Pipelines", "11 Automations", "2 Funnels", "8 Email Templates", "3 Workflows"],
    thumbnailGradient: ["#F97316", "#EAB308"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "16",
    name: "Dental Snapshot",
    slug: "dental",
    industry: "Dental",
    category: "Health & Wellness",
    description: "Dental practice CRM with patient scheduling, recall reminders, and treatment plan follow-ups.",
    longDescription: "Complete dental practice management system. Includes new patient intake forms, appointment scheduling, recall and hygiene reminders, treatment plan acceptance workflows, and patient reactivation campaigns. Perfect for general dentistry, cosmetic, and orthodontic practices.",
    price: 127,
    features: ["New patient intake forms", "Recall & hygiene reminders", "Treatment plan follow-ups", "Patient reactivation campaigns", "Review request automations"],
    includes: ["3 Pipelines", "14 Automations", "2 Funnels", "10 Email Templates", "4 Workflows"],
    thumbnailGradient: ["#06B6D4", "#0EA5E9"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "17",
    name: "Chiropractic Snapshot",
    slug: "chiropractic",
    industry: "Chiropractic",
    category: "Health & Wellness",
    description: "Chiropractic clinic CRM with patient onboarding, care plan tracking, and wellness program management.",
    longDescription: "Designed for chiropractic offices. Manages new patient consultations, care plan tracking, appointment reminders, and wellness membership programs. Includes auto-injury lead capture, corporate wellness outreach, and patient education drip sequences.",
    price: 97,
    features: ["Patient consultation booking", "Care plan tracking", "Wellness membership management", "Auto-injury lead capture", "Patient education sequences"],
    includes: ["3 Pipelines", "12 Automations", "2 Funnels", "8 Email Templates", "3 Workflows"],
    thumbnailGradient: ["#14B8A6", "#06B6D4"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "18",
    name: "Cleaning Service Snapshot",
    slug: "cleaning",
    industry: "Cleaning",
    category: "Home Services",
    description: "Cleaning company CRM with booking management, recurring service tracking, and upsell automations.",
    longDescription: "Perfect for residential and commercial cleaning companies. Handles one-time deep clean bookings, recurring maid service management, move-in/move-out cleaning inquiries, and commercial janitorial contracts. Includes seasonal deep cleaning promotions and referral incentive programs.",
    price: 77,
    features: ["Online booking system", "Recurring service management", "Move-in/out cleaning pipeline", "Commercial contract tracking", "Referral incentive program"],
    includes: ["3 Pipelines", "10 Automations", "2 Funnels", "7 Email Templates", "2 Workflows"],
    thumbnailGradient: ["#A855F7", "#6366F1"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "19",
    name: "Law Firm Snapshot",
    slug: "law-firm",
    industry: "Law Firm",
    category: "Professional Services",
    description: "Law firm CRM with case intake, consultation scheduling, and client communication workflows.",
    longDescription: "Built for law firms and solo practitioners. Manages case intake from multiple channels, free consultation scheduling, retainer agreement tracking, and case status update communications. Includes practice area-specific intake forms for personal injury, family law, criminal defense, and estate planning.",
    price: 147,
    features: ["Multi-channel case intake", "Consultation scheduling", "Retainer tracking pipeline", "Case status communications", "Practice area intake forms"],
    includes: ["4 Pipelines", "14 Automations", "3 Funnels", "10 Email Templates", "4 Workflows"],
    thumbnailGradient: ["#1E293B", "#475569"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "20",
    name: "Auto Detailing Snapshot",
    slug: "auto-detailing",
    industry: "Auto Detailing",
    category: "Local Business",
    description: "Auto detailing CRM with package booking, membership plans, and seasonal promotion campaigns.",
    longDescription: "Designed for mobile and fixed-location auto detailing businesses. Includes package-based booking (basic wash to full ceramic coating), membership plan management, fleet account tracking, and seasonal promotion campaigns. Features before/after gallery workflows and referral programs.",
    price: 77,
    features: ["Package-based booking", "Membership plan management", "Fleet account tracking", "Seasonal promotion campaigns", "Before/after gallery flow"],
    includes: ["3 Pipelines", "10 Automations", "2 Funnels", "7 Email Templates", "2 Workflows"],
    thumbnailGradient: ["#EF4444", "#EC4899"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "21",
    name: "Photography Snapshot",
    slug: "photography",
    industry: "Photography",
    category: "Local Business",
    description: "Photography business CRM with session booking, gallery delivery, and client follow-up automations.",
    longDescription: "Perfect for wedding, portrait, and event photographers. Manages session inquiries, booking confirmations, shot list coordination, gallery delivery workflows, and print order follow-ups. Includes mini-session campaign templates and referral reward automations.",
    price: 97,
    features: ["Session inquiry pipeline", "Booking & contract workflow", "Gallery delivery automations", "Mini-session campaigns", "Referral reward system"],
    includes: ["3 Pipelines", "12 Automations", "2 Funnels", "8 Email Templates", "3 Workflows"],
    thumbnailGradient: ["#F59E0B", "#F97316"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "22",
    name: "Coaching Snapshot",
    slug: "coaching",
    industry: "Coaching",
    category: "Professional Services",
    description: "Life and business coaching CRM with discovery call booking, program enrollment, and client progress tracking.",
    longDescription: "Built for life coaches, business coaches, and consultants. Includes discovery call scheduling, program enrollment pipelines, session reminder automations, client progress check-ins, and testimonial collection workflows. Features webinar registration funnels and course launch sequences.",
    price: 127,
    features: ["Discovery call scheduling", "Program enrollment pipeline", "Session reminder automations", "Progress check-in sequences", "Webinar registration funnels"],
    includes: ["4 Pipelines", "14 Automations", "3 Funnels", "10 Email Templates", "4 Workflows"],
    thumbnailGradient: ["#8B5CF6", "#A855F7"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "23",
    name: "Recruiting Snapshot",
    slug: "recruiting",
    industry: "Recruiting",
    category: "Professional Services",
    description: "Staffing agency CRM with candidate tracking, client management, and placement pipeline workflows.",
    longDescription: "Designed for staffing agencies and independent recruiters. Manages candidate intake, resume screening pipelines, interview scheduling, client job order tracking, and placement follow-ups. Includes candidate nurture sequences and client relationship management workflows.",
    price: 147,
    features: ["Candidate intake pipeline", "Interview scheduling", "Job order tracking", "Placement follow-ups", "Candidate nurture sequences"],
    includes: ["5 Pipelines", "14 Automations", "2 Funnels", "10 Email Templates", "4 Workflows"],
    thumbnailGradient: ["#3B82F6", "#0EA5E9"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "24",
    name: "Tax Preparation Snapshot",
    slug: "tax-prep",
    industry: "Tax Preparation",
    category: "Insurance & Finance",
    description: "Tax prep business CRM with client intake, document collection, and seasonal filing workflows.",
    longDescription: "Built for tax preparation firms and CPAs. Handles client intake, document collection checklists, filing status tracking, and deadline reminder automations. Includes off-season bookkeeping upsell campaigns, estimated tax payment reminders, and year-round client engagement sequences.",
    price: 97,
    features: ["Client intake & document collection", "Filing status tracking", "Deadline reminder automations", "Off-season bookkeeping upsells", "Year-round engagement"],
    includes: ["3 Pipelines", "12 Automations", "2 Funnels", "9 Email Templates", "3 Workflows"],
    thumbnailGradient: ["#059669", "#10B981"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "25",
    name: "Fencing Snapshot",
    slug: "fencing",
    industry: "Fencing",
    category: "Home Services",
    description: "Fencing contractor CRM with estimate management, project scheduling, and material tracking workflows.",
    longDescription: "Purpose-built for fencing companies. Manages estimate requests, on-site measurement scheduling, material selection workflows, project timelines, and warranty registration. Includes seasonal promotion campaigns for privacy fencing, pool enclosures, and commercial security fencing.",
    price: 77,
    features: ["Estimate request pipeline", "On-site measurement scheduling", "Material selection workflow", "Project timeline tracking", "Warranty registration"],
    includes: ["3 Pipelines", "10 Automations", "2 Funnels", "7 Email Templates", "2 Workflows"],
    thumbnailGradient: ["#78716C", "#A8A29E"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
];

export const FAQ_ITEMS: FAQItem[] = [
  {
    question: "What is a GoHighLevel snapshot?",
    answer: "A snapshot is a pre-built template that installs an entire CRM setup into your GoHighLevel sub-account with one click. It includes pipelines, automations, workflows, funnels, email templates, and more — all configured and ready to use for a specific industry.",
  },
  {
    question: "How do I install a snapshot?",
    answer: "After purchasing, you'll receive a GHL snapshot share link. Simply click the link, choose which sub-account to install it into, and everything will be imported automatically. The entire process takes under 5 minutes.",
  },
  {
    question: "Do I need a GoHighLevel account?",
    answer: "Yes, you need an active GoHighLevel account (Agency or SaaS plan) to install snapshots. Each snapshot is installed into a sub-account within your GHL dashboard.",
  },
  {
    question: "Can I customize the snapshot after installing?",
    answer: "Absolutely. Every element of the snapshot — pipelines, automations, funnels, emails, and workflows — is fully editable. The snapshot gives you a professional starting point that you can customize to match your brand and specific business needs.",
  },
  {
    question: "Will installing a snapshot overwrite my existing setup?",
    answer: "No. Snapshots are additive — they add new elements to your sub-account without removing or overwriting anything that's already there. We recommend installing into a fresh sub-account for the cleanest setup.",
  },
  {
    question: "Do you offer refunds?",
    answer: "Due to the digital nature of snapshots (they're instantly delivered and installed), we don't offer refunds once a snapshot has been accessed. However, if you have any issues with installation or setup, our team is here to help.",
  },
  {
    question: "Are updates included?",
    answer: "Each snapshot purchase includes the current version at the time of purchase. Major updates to existing snapshots are offered at a discounted rate to previous buyers.",
  },
  {
    question: "Can I use a snapshot for multiple sub-accounts?",
    answer: "Each snapshot purchase includes a single-use share link. If you need to install the same snapshot into multiple sub-accounts, you can purchase additional licenses at a discounted rate.",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    quote: "Saved me at least 40 hours of setup time. The automations alone were worth every penny — I just had to swap in my branding and I was live.",
    name: "Marcus T.",
    title: "Agency Owner",
    industry: "Marketing Agency",
  },
  {
    quote: "My HVAC client was up and running in under an hour. The pipelines and follow-up sequences are exactly what a service business needs. Highly recommend.",
    name: "Sarah K.",
    title: "GHL Consultant",
    industry: "HVAC",
  },
  {
    quote: "I've bought snapshots from other providers before. These are on another level — the automations actually make sense, and the funnels convert out of the box.",
    name: "David R.",
    title: "SaaS Agency Owner",
    industry: "SaaS Agency",
  },
];

export const STATS: Stat[] = [
  { value: "25+", label: "Industry Snapshots" },
  { value: "500+", label: "Agencies Served" },
  { value: "15+", label: "Industries Covered" },
  { value: "<5min", label: "Average Install Time" },
];

export const CATEGORIES = [
  "All",
  "Home Services",
  "Health & Wellness",
  "Professional Services",
  "Agency",
  "Local Business",
  "Insurance & Finance",
] as const;
