import { Snapshot, FAQItem, Testimonial, Stat } from "./types";

export const SNAPSHOTS: Snapshot[] = [
  {
    id: "1",
    name: "SaaS Agency Snapshot",
    slug: "saas-agency",
    industry: "SaaS Agency",
    category: "Agency",
    description: "The ultimate done-for-you SaaS agency setup with white-label dashboards, onboarding funnels, and year-long nurture campaigns built in.",
    longDescription: "Get your SaaS agency fully operational in under 15 minutes. This premium snapshot comes loaded with two fully optimized agency websites, SaaS checkout and onboarding funnels, a dynamic pricing table, and an eBook lead magnet. It includes extensive workflow automations, fully automated pipelines, instant lead notifications, 52-week SMS and email nurture campaigns, abandoned cart recovery, affiliate manager setup, a white-label support portal with onboarding tutorial videos, and 13 beautifully designed holiday emails. Everything you need to sell, onboard, and retain SaaS clients at scale.",
    price: 597,
    features: [
      "2 Fully Optimized SaaS Agency Websites",
      "SaaS Checkout & Onboarding Funnels",
      "Dynamic SaaS Pricing Table",
      "eBook Lead Magnet",
      "Extensive Workflow Automations",
      "Fully Automated Pipelines",
      "Instant Lead Notifications & Follow-Ups",
      "52 Weekly SMS Nurture Campaigns",
      "52 Email Long-Term Nurture Campaigns",
      "Abandoned Cart Workflow",
      "Missed Call Text Back Sequence",
      "Birthday & Referral Campaigns",
      "Affiliate Manager Setup",
      "White Label Support Portal",
      "White Label Onboarding Tutorial Videos",
      "13 Designed Holiday Emails",
      "5 Facebook Ads",
    ],
    includes: ["2 Websites", "Multiple Funnels", "5+ Pipelines", "18+ Automations", "52 SMS Campaigns", "52 Email Campaigns", "5 Facebook Ads"],
    thumbnailGradient: ["#6366F1", "#8B5CF6"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "2",
    name: "Marketing Agency Snapshot",
    slug: "marketing-agency",
    industry: "Marketing Agency",
    category: "Agency",
    description: "Full-service marketing agency CRM with optimized websites, sales funnels, automated pipelines, and AI chat bot included.",
    longDescription: "Everything a digital marketing agency needs to manage clients and close deals on autopilot. This snapshot includes two fully optimized agency websites, multiple sales funnels, five automated pipelines, four database reactivation campaigns, a 52-week SMS and email campaign series, birthday and referral promos, incoming lead notifications with nurture sequences, appointment workflows, a support portal integration, lead magnets, an AI chat bot, onboarding funnels, reputation management, and 13 beautifully designed holiday emails.",
    price: 597,
    features: [
      "2 Fully Optimized Agency Websites",
      "Fully Optimized Sales Funnels",
      "5 Automated Pipelines",
      "4 Database Reactivation Campaigns",
      "52-Week SMS/Email Campaigns",
      "Birthday Campaign",
      "Customer Referral Campaigns",
      "Incoming Lead Notifications + Nurture",
      "Appointment Workflows",
      "Support Portal Integration",
      "Lead Magnets",
      "AI Chat Bot",
      "Onboarding Funnels",
      "Reputation Management",
      "13 Beautifully Designed Holiday Emails",
    ],
    includes: ["2 Websites", "Sales Funnels", "5 Pipelines", "4 DB Reactivation Campaigns", "52 SMS Campaigns", "52 Email Campaigns", "AI Chat Bot"],
    thumbnailGradient: ["#3B82F6", "#6366F1"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "3",
    name: "Solar Snapshot",
    slug: "solar",
    industry: "Solar",
    category: "Home Services",
    description: "Purpose-built for solar companies with optimized website, lead gen funnels, automated pipelines, and year-long nurture campaigns.",
    longDescription: "Built specifically for solar installation companies looking to automate their entire sales process. This snapshot includes a fully optimized solar website, seven or more high-converting lead generation funnels, extensive workflow automations, fully automated pipelines, instant lead notifications and follow-ups, appointment confirmations and reminders, 52-week SMS and email nurture campaigns, birthday and referral promo campaigns, invoice reminders, database reactivation, reputation management, review request campaigns, holiday emails, missed call text back, and Facebook ad creatives.",
    price: 497,
    features: [
      "Fully Optimized Solar Website",
      "7+ High Converting Lead Generating Funnels",
      "Extensive Workflow Automations",
      "Fully Automated Pipelines",
      "Instant Lead Notifications & Follow-Ups",
      "Appointment Confirmations + Reminders",
      "52 Weekly SMS Nurture Campaigns",
      "52 Email Long-Term Nurture Campaigns",
      "Birthday & Referral Promo Campaigns",
      "Invoice Reminders / Refund / Cancellation",
      "Database Reactivation",
      "Ongoing Reputation Management",
      "Advanced Review Request Campaign",
      "13 Designed Holiday Emails",
      "Advanced Missed Call Text Back",
      "5 Facebook Ads",
    ],
    includes: ["1 Website", "7+ Funnels", "Automated Pipelines", "52 SMS Campaigns", "52 Email Campaigns", "Reputation Management", "5 Facebook Ads"],
    thumbnailGradient: ["#F59E0B", "#EF4444"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "4",
    name: "Plumbing Snapshot",
    slug: "plumbing",
    industry: "Plumbing",
    category: "Home Services",
    description: "Complete plumbing business CRM with lead gen funnels, service follow-ups, invoice reminders, and database reactivation built in.",
    longDescription: "Built for plumbing companies of all sizes. Comes with a fully optimized plumber website, five high-converting lead generation funnels, extensive workflow automations, fully automated pipelines, instant lead notifications, service follow-up sequences, appointment confirmations and reminders, 52-week SMS and email nurture campaigns, invoice reminders with refund and cancellation handling, database reactivation, birthday and referral promo campaigns, advanced missed call text back, ongoing reputation management, review request campaigns, 13 holiday emails, and five Facebook ad creatives.",
    price: 497,
    features: [
      "Fully Optimized Plumber Website",
      "5 High Converting Lead Generating Funnels",
      "Extensive Workflow Automations",
      "Fully Automated Pipelines",
      "Instant Lead Notifications & Follow-Ups",
      "Service Follow-Up Sequences",
      "Appointment Confirmations + Reminders",
      "52 Weekly SMS Nurture Campaigns",
      "52 Email Long-Term Nurture Campaigns",
      "Invoice Reminders / Refund / Cancellation",
      "Database Reactivation",
      "Birthday & Referral Promo Campaigns",
      "Advanced Missed Call Text Back",
      "Ongoing Reputation Management",
      "Advanced Review Request Campaign",
      "13 Designed Holiday Emails",
      "5 Facebook Ads",
    ],
    includes: ["1 Website", "5 Funnels", "Automated Pipelines", "52 SMS Campaigns", "52 Email Campaigns", "Reputation Management", "5 Facebook Ads"],
    thumbnailGradient: ["#3B82F6", "#0EA5E9"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "5",
    name: "Pest Control Snapshot",
    slug: "pest-control",
    industry: "Pest Control",
    category: "Home Services",
    description: "Pest control CRM with optimized website, lead funnels, appointment automations, and year-long SMS/email campaigns ready to go.",
    longDescription: "Designed for pest control operators looking to grow and automate. This snapshot includes a fully optimized website, five high-converting lead generation funnels, extensive workflow automations, fully automated pipelines, instant lead notifications, appointment confirmations and reminders, 52-week SMS and email nurture campaigns, birthday and referral promo campaigns, invoice reminders, database reactivation, advanced missed call text back, ongoing reputation management, advanced review request campaigns, 13 holiday email templates, and five Facebook ad creatives.",
    price: 497,
    features: [
      "Fully Optimized Pest Control Website",
      "5 High Converting Lead Generating Funnels",
      "Extensive Workflow Automations",
      "Fully Automated Pipelines",
      "Instant Lead Notifications & Follow-Ups",
      "Appointment Confirmations + Reminders",
      "52 Weekly SMS Nurture Campaigns",
      "52 Email Long-Term Nurture Campaigns",
      "Birthday & Referral Promo Campaigns",
      "Invoice Reminders / Refund / Cancellation",
      "Database Reactivation",
      "Advanced Missed Call Text Back",
      "Ongoing Reputation Management",
      "Advanced Review Request Campaign",
      "13 Designed Holiday Emails",
      "5 Facebook Ads",
    ],
    includes: ["1 Website", "5 Funnels", "Automated Pipelines", "52 SMS Campaigns", "52 Email Campaigns", "Reputation Management", "5 Facebook Ads"],
    thumbnailGradient: ["#EF4444", "#F97316"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "6",
    name: "HVAC Snapshot",
    slug: "hvac",
    industry: "HVAC",
    category: "Home Services",
    description: "HVAC company CRM with emergency service follow-ups, lead gen funnels, invoice reminders, and full reputation management.",
    longDescription: "Complete HVAC business management system built for heating and cooling companies. Includes a fully optimized HVAC website, five high-converting lead generation funnels, extensive workflow automations with emergency service follow-up, fully automated pipelines, instant lead notifications, appointment confirmations and reminders, 52-week SMS and email nurture campaigns, birthday and referral promo campaigns, invoice reminders with refund and cancellation workflows, database reactivation, ongoing reputation management, advanced review request campaigns, 13 holiday emails, missed call text back, and five Facebook ad creatives.",
    price: 497,
    features: [
      "Fully Optimized HVAC Website",
      "5 High Converting Lead Generating Funnels",
      "Extensive Workflow Automations",
      "Emergency Service Follow-Up",
      "Fully Automated Pipelines",
      "Instant Lead Notifications & Follow-Ups",
      "Appointment Confirmations + Reminders",
      "52 Weekly SMS Nurture Campaigns",
      "52 Email Long-Term Nurture Campaigns",
      "Birthday & Referral Promo Campaigns",
      "Invoice Reminders / Refund / Cancellation",
      "Database Reactivation",
      "Ongoing Reputation Management",
      "Advanced Review Request Campaign",
      "13 Designed Holiday Emails",
      "Advanced Missed Call Text Back",
      "5 Facebook Ads",
    ],
    includes: ["1 Website", "5 Funnels", "Automated Pipelines", "52 SMS Campaigns", "52 Email Campaigns", "Reputation Management", "5 Facebook Ads"],
    thumbnailGradient: ["#0EA5E9", "#6366F1"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "7",
    name: "Roofing Snapshot",
    slug: "roofing",
    industry: "Roofing",
    category: "Home Services",
    description: "Roofing contractor CRM with lead gen funnels, automated pipelines, estimate follow-ups, and full nurture campaign suite.",
    longDescription: "Built for roofing contractors handling residential and commercial projects. This snapshot comes with a fully optimized roofing website, five high-converting lead generation funnels, extensive workflow automations, fully automated pipelines, instant lead notifications and follow-ups, appointment confirmations and reminders, 52-week SMS and email nurture campaigns, birthday and referral promo campaigns, invoice reminders, database reactivation, ongoing reputation management, advanced review request campaigns, 13 holiday emails, missed call text back, and five Facebook ad creatives.",
    price: 497,
    features: [
      "Fully Optimized Roofing Website",
      "5 High Converting Lead Generating Funnels",
      "Extensive Workflow Automations",
      "Fully Automated Pipelines",
      "Instant Lead Notifications & Follow-Ups",
      "Appointment Confirmations + Reminders",
      "52 Weekly SMS Nurture Campaigns",
      "52 Email Long-Term Nurture Campaigns",
      "Birthday & Referral Promo Campaigns",
      "Invoice Reminders / Refund / Cancellation",
      "Database Reactivation",
      "Ongoing Reputation Management",
      "Advanced Review Request Campaign",
      "13 Designed Holiday Emails",
      "Advanced Missed Call Text Back",
      "5 Facebook Ads",
    ],
    includes: ["1 Website", "5 Funnels", "Automated Pipelines", "52 SMS Campaigns", "52 Email Campaigns", "Reputation Management", "5 Facebook Ads"],
    thumbnailGradient: ["#DC2626", "#9333EA"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "8",
    name: "Landscaping Snapshot",
    slug: "landscaping",
    industry: "Landscaping",
    category: "Home Services",
    description: "Landscaping business CRM with optimized website, lead funnels, seasonal campaigns, and automated follow-up sequences.",
    longDescription: "Everything a landscaping company needs to generate leads and keep clients coming back. Includes a fully optimized landscaping website, five high-converting lead generation funnels, extensive workflow automations, fully automated pipelines, instant lead notifications, appointment confirmations and reminders, 52-week SMS and email nurture campaigns, birthday and referral promo campaigns, invoice reminders, database reactivation, ongoing reputation management, advanced review request campaigns, 13 holiday emails, missed call text back, and five Facebook ad creatives.",
    price: 497,
    features: [
      "Fully Optimized Landscaping Website",
      "5 High Converting Lead Generating Funnels",
      "Extensive Workflow Automations",
      "Fully Automated Pipelines",
      "Instant Lead Notifications & Follow-Ups",
      "Appointment Confirmations + Reminders",
      "52 Weekly SMS Nurture Campaigns",
      "52 Email Long-Term Nurture Campaigns",
      "Birthday & Referral Promo Campaigns",
      "Invoice Reminders / Refund / Cancellation",
      "Database Reactivation",
      "Ongoing Reputation Management",
      "Advanced Review Request Campaign",
      "13 Designed Holiday Emails",
      "Advanced Missed Call Text Back",
      "5 Facebook Ads",
    ],
    includes: ["1 Website", "5 Funnels", "Automated Pipelines", "52 SMS Campaigns", "52 Email Campaigns", "Reputation Management", "5 Facebook Ads"],
    thumbnailGradient: ["#22C55E", "#10B981"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "9",
    name: "Electrician Snapshot",
    slug: "electrician",
    industry: "Electrician",
    category: "Home Services",
    description: "Electrician CRM with lead gen funnels, service call management, automated pipelines, and full review management system.",
    longDescription: "Designed for electrical contractors handling residential and commercial work. This snapshot includes a fully optimized electrician website, five high-converting lead generation funnels, extensive workflow automations, fully automated pipelines, instant lead notifications, appointment confirmations and reminders, 52-week SMS and email nurture campaigns, birthday and referral promo campaigns, invoice reminders, database reactivation, ongoing reputation management, advanced review request campaigns, 13 holiday emails, missed call text back, and five Facebook ad creatives.",
    price: 497,
    features: [
      "Fully Optimized Electrician Website",
      "5 High Converting Lead Generating Funnels",
      "Extensive Workflow Automations",
      "Fully Automated Pipelines",
      "Instant Lead Notifications & Follow-Ups",
      "Appointment Confirmations + Reminders",
      "52 Weekly SMS Nurture Campaigns",
      "52 Email Long-Term Nurture Campaigns",
      "Birthday & Referral Promo Campaigns",
      "Invoice Reminders / Refund / Cancellation",
      "Database Reactivation",
      "Ongoing Reputation Management",
      "Advanced Review Request Campaign",
      "13 Designed Holiday Emails",
      "Advanced Missed Call Text Back",
      "5 Facebook Ads",
    ],
    includes: ["1 Website", "5 Funnels", "Automated Pipelines", "52 SMS Campaigns", "52 Email Campaigns", "Reputation Management", "5 Facebook Ads"],
    thumbnailGradient: ["#F59E0B", "#EAB308"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "10",
    name: "Restaurant Snapshot",
    slug: "restaurant",
    industry: "Restaurant",
    category: "Local Business",
    description: "Restaurant CRM with reservation funnels, loyalty campaigns, event booking workflows, and automated review management.",
    longDescription: "Complete restaurant management system designed to fill tables and keep customers coming back. Includes a fully optimized restaurant website, five high-converting funnels, extensive workflow automations, fully automated pipelines, instant lead notifications, appointment confirmations and reminders, 52-week SMS and email nurture campaigns, birthday and referral promo campaigns, database reactivation, ongoing reputation management, advanced review request campaigns, 13 holiday emails, missed call text back, and five Facebook ad creatives.",
    price: 497,
    features: [
      "Fully Optimized Restaurant Website",
      "5 High Converting Funnels",
      "Extensive Workflow Automations",
      "Fully Automated Pipelines",
      "Instant Lead Notifications & Follow-Ups",
      "Appointment Confirmations + Reminders",
      "52 Weekly SMS Nurture Campaigns",
      "52 Email Long-Term Nurture Campaigns",
      "Birthday & Referral Promo Campaigns",
      "Database Reactivation",
      "Ongoing Reputation Management",
      "Advanced Review Request Campaign",
      "13 Designed Holiday Emails",
      "Advanced Missed Call Text Back",
      "5 Facebook Ads",
    ],
    includes: ["1 Website", "5 Funnels", "Automated Pipelines", "52 SMS Campaigns", "52 Email Campaigns", "Reputation Management", "5 Facebook Ads"],
    thumbnailGradient: ["#EF4444", "#F97316"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "11",
    name: "Med Spa Snapshot",
    slug: "med-spa",
    industry: "Med Spa",
    category: "Health & Wellness",
    description: "Med spa CRM with treatment booking funnels, membership management, patient follow-up sequences, and review campaigns.",
    longDescription: "Purpose-built for medical spas and aesthetic clinics looking to book more treatments and retain clients. Includes a fully optimized med spa website, five high-converting funnels, extensive workflow automations, fully automated pipelines, instant lead notifications, appointment confirmations and reminders, 52-week SMS and email nurture campaigns, birthday and referral promo campaigns, database reactivation, ongoing reputation management, advanced review request campaigns, 13 holiday emails, missed call text back, and five Facebook ad creatives.",
    price: 497,
    features: [
      "Fully Optimized Med Spa Website",
      "5 High Converting Funnels",
      "Extensive Workflow Automations",
      "Fully Automated Pipelines",
      "Instant Lead Notifications & Follow-Ups",
      "Appointment Confirmations + Reminders",
      "52 Weekly SMS Nurture Campaigns",
      "52 Email Long-Term Nurture Campaigns",
      "Birthday & Referral Promo Campaigns",
      "Database Reactivation",
      "Ongoing Reputation Management",
      "Advanced Review Request Campaign",
      "13 Designed Holiday Emails",
      "Advanced Missed Call Text Back",
      "5 Facebook Ads",
    ],
    includes: ["1 Website", "5 Funnels", "Automated Pipelines", "52 SMS Campaigns", "52 Email Campaigns", "Reputation Management", "5 Facebook Ads"],
    thumbnailGradient: ["#EC4899", "#A855F7"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "12",
    name: "Fitness Snapshot",
    slug: "fitness",
    industry: "Fitness",
    category: "Health & Wellness",
    description: "Gym and fitness studio CRM with membership funnels, class booking, retention automations, and full nurture campaigns.",
    longDescription: "Built for gyms, CrossFit boxes, yoga studios, and personal trainers. Includes a fully optimized fitness website, five high-converting funnels, extensive workflow automations, fully automated pipelines, instant lead notifications, appointment confirmations and reminders, 52-week SMS and email nurture campaigns, birthday and referral promo campaigns, database reactivation, ongoing reputation management, advanced review request campaigns, 13 holiday emails, missed call text back, and five Facebook ad creatives.",
    price: 497,
    features: [
      "Fully Optimized Fitness Website",
      "5 High Converting Funnels",
      "Extensive Workflow Automations",
      "Fully Automated Pipelines",
      "Instant Lead Notifications & Follow-Ups",
      "Appointment Confirmations + Reminders",
      "52 Weekly SMS Nurture Campaigns",
      "52 Email Long-Term Nurture Campaigns",
      "Birthday & Referral Promo Campaigns",
      "Database Reactivation",
      "Ongoing Reputation Management",
      "Advanced Review Request Campaign",
      "13 Designed Holiday Emails",
      "Advanced Missed Call Text Back",
      "5 Facebook Ads",
    ],
    includes: ["1 Website", "5 Funnels", "Automated Pipelines", "52 SMS Campaigns", "52 Email Campaigns", "Reputation Management", "5 Facebook Ads"],
    thumbnailGradient: ["#8B5CF6", "#EC4899"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "13",
    name: "Life Insurance Snapshot",
    slug: "life-insurance",
    industry: "Life Insurance",
    category: "Insurance & Finance",
    description: "Premium life insurance CRM with two websites, eight funnels, seven pipelines, ChatGPT AI assistant, and power dialer campaigns.",
    longDescription: "A premium snapshot designed for life insurance agents and agencies looking to dominate their market. Comes loaded with two fully optimized websites, eight high-converting funnels, extensive workflow automations, seven fully automated pipelines, a ChatGPT AI assistant, appointment confirmations and reminders, 52-week SMS and email nurture campaigns, birthday and referral promo campaigns, power dialer campaigns, four database reactivation campaigns, advanced review request campaigns, 13 holiday emails, missed call text back, and five Facebook ad creatives.",
    price: 597,
    features: [
      "2 Fully Optimized Websites",
      "8 High Converting Funnels",
      "Extensive Workflow Automations",
      "7 Fully Automated Pipelines",
      "ChatGPT AI Assistant",
      "Appointment Confirmations + Reminders",
      "52 Weekly SMS Nurture Campaigns",
      "52 Email Long-Term Nurture Campaigns",
      "Birthday & Referral Promo Campaigns",
      "Power Dialer Campaigns",
      "4 Database Reactivation Campaigns",
      "Advanced Review Request Campaign",
      "13 Designed Holiday Emails",
      "Advanced Missed Call Text Back",
      "5 Facebook Ads",
    ],
    includes: ["2 Websites", "8 Funnels", "7 Pipelines", "AI Assistant", "Power Dialer", "52 SMS Campaigns", "52 Email Campaigns", "5 Facebook Ads"],
    thumbnailGradient: ["#0EA5E9", "#3B82F6"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "14",
    name: "Real Estate Snapshot",
    slug: "real-estate",
    industry: "Real Estate",
    category: "Professional Services",
    description: "Real estate agent CRM with buyer/seller funnels, showing scheduling, drip campaigns, and automated follow-up sequences.",
    longDescription: "Complete real estate CRM for agents and brokerages looking to close more deals. Includes a fully optimized real estate website, five high-converting funnels, extensive workflow automations, fully automated pipelines, instant lead notifications, appointment confirmations and reminders, 52-week SMS and email nurture campaigns, birthday and referral promo campaigns, database reactivation, ongoing reputation management, advanced review request campaigns, 13 holiday emails, missed call text back, and five Facebook ad creatives.",
    price: 497,
    features: [
      "Fully Optimized Real Estate Website",
      "5 High Converting Funnels",
      "Extensive Workflow Automations",
      "Fully Automated Pipelines",
      "Instant Lead Notifications & Follow-Ups",
      "Appointment Confirmations + Reminders",
      "52 Weekly SMS Nurture Campaigns",
      "52 Email Long-Term Nurture Campaigns",
      "Birthday & Referral Promo Campaigns",
      "Database Reactivation",
      "Ongoing Reputation Management",
      "Advanced Review Request Campaign",
      "13 Designed Holiday Emails",
      "Advanced Missed Call Text Back",
      "5 Facebook Ads",
    ],
    includes: ["1 Website", "5 Funnels", "Automated Pipelines", "52 SMS Campaigns", "52 Email Campaigns", "Reputation Management", "5 Facebook Ads"],
    thumbnailGradient: ["#10B981", "#059669"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "15",
    name: "Home Improvement Snapshot",
    slug: "home-improvement",
    industry: "Home Improvement",
    category: "Home Services",
    description: "Home improvement contractor CRM with estimate funnels, project pipelines, invoice reminders, and full nurture suite.",
    longDescription: "Built for general contractors and home improvement companies. Includes a fully optimized website, five high-converting lead generation funnels, extensive workflow automations, fully automated pipelines, instant lead notifications, appointment confirmations and reminders, 52-week SMS and email nurture campaigns, birthday and referral promo campaigns, invoice reminders, database reactivation, ongoing reputation management, advanced review request campaigns, 13 holiday emails, missed call text back, and five Facebook ad creatives.",
    price: 497,
    features: [
      "Fully Optimized Home Improvement Website",
      "5 High Converting Lead Generating Funnels",
      "Extensive Workflow Automations",
      "Fully Automated Pipelines",
      "Instant Lead Notifications & Follow-Ups",
      "Appointment Confirmations + Reminders",
      "52 Weekly SMS Nurture Campaigns",
      "52 Email Long-Term Nurture Campaigns",
      "Birthday & Referral Promo Campaigns",
      "Invoice Reminders / Refund / Cancellation",
      "Database Reactivation",
      "Ongoing Reputation Management",
      "Advanced Review Request Campaign",
      "13 Designed Holiday Emails",
      "Advanced Missed Call Text Back",
      "5 Facebook Ads",
    ],
    includes: ["1 Website", "5 Funnels", "Automated Pipelines", "52 SMS Campaigns", "52 Email Campaigns", "Reputation Management", "5 Facebook Ads"],
    thumbnailGradient: ["#F97316", "#EAB308"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "16",
    name: "Dentist Snapshot",
    slug: "dental",
    industry: "Dental",
    category: "Health & Wellness",
    description: "Premium dental practice CRM with new patient onboarding, post-treatment follow-ups, six pipelines, and billing reminders.",
    longDescription: "A premium snapshot designed specifically for dental practices. Comes with a dentist website, five high-converting funnels, a new patient onboarding series, post-treatment follow-up sequences, payment and billing reminders, extensive workflow automations, six fully automated pipelines, appointment confirmations and reminders, 52-week SMS and email nurture campaigns, birthday and referral promo campaigns, four database reactivation campaigns, review campaigns, 13 holiday emails, missed call text back, and five Facebook ad creatives.",
    price: 597,
    features: [
      "Fully Optimized Dentist Website",
      "5 High Converting Funnels",
      "New Patient Onboarding Series",
      "Post-Treatment Follow-Up",
      "Payment & Billing Reminders",
      "Extensive Workflow Automations",
      "6 Fully Automated Pipelines",
      "Appointment Confirmations + Reminders",
      "52 Weekly SMS Nurture Campaigns",
      "52 Email Long-Term Nurture Campaigns",
      "Birthday & Referral Promo Campaigns",
      "4 Database Reactivation Campaigns",
      "Review Campaign",
      "13 Designed Holiday Emails",
      "Advanced Missed Call Text Back",
      "5 Facebook Ad Creatives",
    ],
    includes: ["1 Website", "5 Funnels", "6 Pipelines", "Patient Onboarding", "52 SMS Campaigns", "52 Email Campaigns", "5 Facebook Ads"],
    thumbnailGradient: ["#06B6D4", "#0EA5E9"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "17",
    name: "Chiropractor Snapshot",
    slug: "chiropractic",
    industry: "Chiropractic",
    category: "Health & Wellness",
    description: "Premium chiropractor CRM with ten pipelines, patient onboarding, post-appointment check-ups, and inactive patient surveys.",
    longDescription: "A premium snapshot built for chiropractic offices that want to automate patient management from first visit to long-term care. Includes a chiropractor website, six high-converting funnels, new patient onboarding series, inactive patient survey workflow, post-appointment check-up sequences, pre-appointment instructions, payment and billing reminders, extensive workflow automations, ten fully automated pipelines, appointment confirmations and reminders, 52-week SMS and email nurture campaigns, birthday and referral promo campaigns, four database reactivation campaigns, review campaigns, 13 holiday emails, and five Facebook ad creatives.",
    price: 597,
    features: [
      "Fully Optimized Chiropractor Website",
      "6 High Converting Funnels",
      "New Patient Onboarding Series",
      "Inactive Patient Survey Workflow",
      "Post-Appointment Check-Up",
      "Pre-Appointment Instructions",
      "Payment & Billing Reminders",
      "Extensive Workflow Automations",
      "10 Fully Automated Pipelines",
      "Appointment Confirmations + Reminders",
      "52 Weekly SMS Nurture Campaigns",
      "52 Email Long-Term Nurture Campaigns",
      "Birthday & Referral Promo Campaigns",
      "4 Database Reactivation Campaigns",
      "Review Campaign",
      "13 Designed Holiday Emails",
      "5 Facebook Ad Creatives",
    ],
    includes: ["1 Website", "6 Funnels", "10 Pipelines", "Patient Onboarding", "52 SMS Campaigns", "52 Email Campaigns", "5 Facebook Ads"],
    thumbnailGradient: ["#14B8A6", "#06B6D4"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "18",
    name: "Cleaning Snapshot",
    slug: "cleaning",
    industry: "Cleaning",
    category: "Home Services",
    description: "Cleaning company CRM with booking funnels, service follow-ups, abandoned estimate recovery, and full nurture campaigns.",
    longDescription: "Perfect for residential and commercial cleaning companies. Includes a fully optimized cleaning website, five high-converting funnels, payment and billing reminders, extensive workflow automations, fully automated pipelines, appointment confirmations and reminders, 52-week SMS and email nurture campaigns, birthday and referral promo campaigns, abandoned estimate follow-up, four database reactivation campaigns, review campaigns, 13 holiday emails, missed call text back, and Facebook ad creatives.",
    price: 497,
    features: [
      "Fully Optimized Cleaning Website",
      "5 High Converting Funnels",
      "Payment & Billing Reminders",
      "Extensive Workflow Automations",
      "Fully Automated Pipelines",
      "Appointment Confirmations + Reminders",
      "52 Weekly SMS Nurture Campaigns",
      "52 Email Long-Term Nurture Campaigns",
      "Birthday & Referral Promo Campaigns",
      "Abandoned Estimate Follow-Up",
      "4 Database Reactivation Campaigns",
      "Review Campaign",
      "13 Designed Holiday Emails",
      "Advanced Missed Call Text Back",
      "5 Facebook Ad Creatives",
    ],
    includes: ["1 Website", "5 Funnels", "Automated Pipelines", "52 SMS Campaigns", "52 Email Campaigns", "4 DB Reactivation Campaigns", "5 Facebook Ads"],
    thumbnailGradient: ["#A855F7", "#6366F1"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "19",
    name: "Lawyers Snapshot",
    slug: "lawyers",
    industry: "Lawyers",
    category: "Professional Services",
    description: "Law firm CRM with optimized websites, automated pipelines, AI chat bot, and full 52-week nurture campaign suite.",
    longDescription: "Built for law firms and solo practitioners looking to automate client intake and case management. Includes two fully optimized websites, automated pipelines, database reactivation campaigns, 52-week SMS and email campaigns, birthday campaign, incoming lead notifications, appointment workflows, an AI chat bot, custom values, tags, forms, surveys, and 13 beautifully designed holiday emails.",
    price: 397,
    features: [
      "2 Fully Optimized Websites",
      "Automated Pipelines",
      "Database Reactivation Campaigns",
      "52-Week SMS/Email Campaigns",
      "Birthday Campaign",
      "Incoming Lead Notifications",
      "Appointment Workflows",
      "AI Chat Bot",
      "Custom Values, Tags, Forms & Surveys",
      "13 Beautifully Designed Holiday Emails",
    ],
    includes: ["2 Websites", "Automated Pipelines", "DB Reactivation Campaigns", "52 SMS Campaigns", "52 Email Campaigns", "AI Chat Bot", "Holiday Emails"],
    thumbnailGradient: ["#1E293B", "#475569"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "20",
    name: "Auto Detailing Snapshot",
    slug: "auto-detailing",
    industry: "Auto Detailing",
    category: "Local Business",
    description: "Auto detailing CRM with booking funnels, membership automations, review campaigns, and year-long nurture sequences.",
    longDescription: "Designed for mobile and fixed-location auto detailing businesses. Includes a fully optimized website, five high-converting funnels, extensive workflow automations, fully automated pipelines, instant lead notifications, appointment confirmations and reminders, 52-week SMS and email nurture campaigns, birthday and referral promo campaigns, database reactivation, ongoing reputation management, advanced review request campaigns, 13 holiday emails, missed call text back, and five Facebook ad creatives.",
    price: 497,
    features: [
      "Fully Optimized Auto Detailing Website",
      "5 High Converting Funnels",
      "Extensive Workflow Automations",
      "Fully Automated Pipelines",
      "Instant Lead Notifications & Follow-Ups",
      "Appointment Confirmations + Reminders",
      "52 Weekly SMS Nurture Campaigns",
      "52 Email Long-Term Nurture Campaigns",
      "Birthday & Referral Promo Campaigns",
      "Database Reactivation",
      "Ongoing Reputation Management",
      "Advanced Review Request Campaign",
      "13 Designed Holiday Emails",
      "Advanced Missed Call Text Back",
      "5 Facebook Ads",
    ],
    includes: ["1 Website", "5 Funnels", "Automated Pipelines", "52 SMS Campaigns", "52 Email Campaigns", "Reputation Management", "5 Facebook Ads"],
    thumbnailGradient: ["#EF4444", "#EC4899"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "21",
    name: "Painter Snapshot",
    slug: "painter",
    industry: "Painter",
    category: "Home Services",
    description: "Painting company CRM with estimate follow-ups, job completion feedback, billing reminders, and full nurture campaigns.",
    longDescription: "Built for residential and commercial painting companies. Includes a painter website, five high-converting funnels, payment and billing reminders, job completion feedback and review requests, abandoned estimate follow-up, extensive workflow automations, fully automated pipelines, appointment confirmations and reminders, 52-week SMS and email nurture campaigns, birthday and referral promo campaigns, four database reactivation campaigns, review campaigns, 13 holiday emails, missed call text back, and five Facebook ad creatives.",
    price: 497,
    features: [
      "Fully Optimized Painter Website",
      "5 High Converting Funnels",
      "Payment & Billing Reminders",
      "Job Completion Feedback & Review Request",
      "Abandoned Estimate Follow-Up",
      "Extensive Workflow Automations",
      "Fully Automated Pipelines",
      "Appointment Confirmations + Reminders",
      "52 Weekly SMS Nurture Campaigns",
      "52 Email Long-Term Nurture Campaigns",
      "Birthday & Referral Promo Campaigns",
      "4 Database Reactivation Campaigns",
      "Review Campaign",
      "13 Designed Holiday Emails",
      "Advanced Missed Call Text Back",
      "5 Facebook Ad Creatives",
    ],
    includes: ["1 Website", "5 Funnels", "Automated Pipelines", "52 SMS Campaigns", "52 Email Campaigns", "4 DB Reactivation Campaigns", "5 Facebook Ads"],
    thumbnailGradient: ["#F59E0B", "#F97316"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "22",
    name: "Hair Salon Snapshot",
    slug: "hair-salon",
    industry: "Hair Salon",
    category: "Local Business",
    description: "Hair salon CRM with appointment funnels, billing reminders, review requests, and year-long client nurture campaigns.",
    longDescription: "Designed for hair salons and barbershops looking to fill their chairs and keep clients rebooking. Includes a hair salon website, five high-converting funnels, payment and billing reminders, job completion feedback and review requests, extensive workflow automations, fully automated pipelines, appointment confirmations and reminders, 52-week SMS and email nurture campaigns, birthday and referral promo campaigns, abandoned estimate follow-up, four database reactivation campaigns, review campaigns, 13 holiday emails, missed call text back, and five Facebook ad creatives.",
    price: 497,
    features: [
      "Fully Optimized Hair Salon Website",
      "5 High Converting Funnels",
      "Payment & Billing Reminders",
      "Job Completion Feedback & Review Request",
      "Abandoned Estimate Follow-Up",
      "Extensive Workflow Automations",
      "Fully Automated Pipelines",
      "Appointment Confirmations + Reminders",
      "52 Weekly SMS Nurture Campaigns",
      "52 Email Long-Term Nurture Campaigns",
      "Birthday & Referral Promo Campaigns",
      "4 Database Reactivation Campaigns",
      "Review Campaign",
      "13 Designed Holiday Emails",
      "Advanced Missed Call Text Back",
      "5 Facebook Ad Creatives",
    ],
    includes: ["1 Website", "5 Funnels", "Automated Pipelines", "52 SMS Campaigns", "52 Email Campaigns", "4 DB Reactivation Campaigns", "5 Facebook Ads"],
    thumbnailGradient: ["#EC4899", "#F472B6"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "23",
    name: "Pet Grooming Snapshot",
    slug: "pet-grooming",
    industry: "Pet Grooming",
    category: "Local Business",
    description: "Pet grooming CRM with booking funnels, billing reminders, abandoned estimate recovery, and full review management.",
    longDescription: "Perfect for pet grooming salons and mobile groomers. Includes a pet grooming website, five high-converting funnels, payment and billing reminders, extensive workflow automations, fully automated pipelines, appointment confirmations and reminders, 52-week SMS and email nurture campaigns, birthday and referral promo campaigns, abandoned estimate follow-up, four database reactivation campaigns, review campaigns, 13 holiday emails, and missed call text back.",
    price: 497,
    features: [
      "Fully Optimized Pet Grooming Website",
      "5 High Converting Funnels",
      "Payment & Billing Reminders",
      "Extensive Workflow Automations",
      "Fully Automated Pipelines",
      "Appointment Confirmations + Reminders",
      "52 Weekly SMS Nurture Campaigns",
      "52 Email Long-Term Nurture Campaigns",
      "Birthday & Referral Promo Campaigns",
      "Abandoned Estimate Follow-Up",
      "4 Database Reactivation Campaigns",
      "Review Campaign",
      "13 Designed Holiday Emails",
      "Advanced Missed Call Text Back",
    ],
    includes: ["1 Website", "5 Funnels", "Automated Pipelines", "52 SMS Campaigns", "52 Email Campaigns", "4 DB Reactivation Campaigns", "Holiday Emails"],
    thumbnailGradient: ["#F59E0B", "#22C55E"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "24",
    name: "Mechanic Snapshot",
    slug: "mechanic",
    industry: "Mechanic",
    category: "Local Business",
    description: "Auto repair CRM with service follow-ups, new customer welcome sequences, billing reminders, and full nurture campaigns.",
    longDescription: "Built for auto repair shops and mechanics looking to automate their customer journey. Includes a mechanic website, five high-converting funnels, payment and billing reminders, after service follow-up, new customer welcome sequence, extensive workflow automations, fully automated pipelines, appointment confirmations and reminders, 52-week SMS and email nurture campaigns, birthday and referral promo campaigns, abandoned estimate follow-up, four database reactivation campaigns, review campaigns, 13 holiday emails, and missed call text back.",
    price: 497,
    features: [
      "Fully Optimized Mechanic Website",
      "5 High Converting Funnels",
      "Payment & Billing Reminders",
      "After Service Follow-Up",
      "New Customer Welcome Sequence",
      "Extensive Workflow Automations",
      "Fully Automated Pipelines",
      "Appointment Confirmations + Reminders",
      "52 Weekly SMS Nurture Campaigns",
      "52 Email Long-Term Nurture Campaigns",
      "Birthday & Referral Promo Campaigns",
      "Abandoned Estimate Follow-Up",
      "4 Database Reactivation Campaigns",
      "Review Campaign",
      "13 Designed Holiday Emails",
      "Advanced Missed Call Text Back",
    ],
    includes: ["1 Website", "5 Funnels", "Automated Pipelines", "52 SMS Campaigns", "52 Email Campaigns", "4 DB Reactivation Campaigns", "Holiday Emails"],
    thumbnailGradient: ["#64748B", "#475569"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "25",
    name: "Pressure Washing Snapshot",
    slug: "pressure-washing",
    industry: "Pressure Washing",
    category: "Home Services",
    description: "Pressure washing CRM with lead gen funnels, invoice reminders, reputation management, and 52-week nurture campaigns.",
    longDescription: "Designed for pressure washing and power washing businesses. Includes five high-converting lead generation funnels, extensive workflow automations, fully automated pipelines, instant lead notifications and follow-ups, appointment confirmations and reminders, 52-week SMS and email nurture campaigns, birthday and referral promo campaigns, invoice reminders with refund and cancellation handling, database reactivation, ongoing reputation management, advanced review request campaigns, 13 holiday emails, missed call text back, and five Facebook ad creatives.",
    price: 497,
    features: [
      "5 High Converting Lead Generating Funnels",
      "Extensive Workflow Automations",
      "Fully Automated Pipelines",
      "Instant Lead Notifications & Follow-Ups",
      "Appointment Confirmations + Reminders",
      "52 Weekly SMS Nurture Campaigns",
      "52 Email Long-Term Nurture Campaigns",
      "Birthday & Referral Promo Campaigns",
      "Invoice Reminders / Refunds / Cancellations",
      "Database Reactivation",
      "Ongoing Reputation Management",
      "Advanced Review Request Campaign",
      "13 Designed Holiday Emails",
      "Advanced Missed Call Text Back",
      "5 Facebook Ads",
    ],
    includes: ["5 Funnels", "Automated Pipelines", "52 SMS Campaigns", "52 Email Campaigns", "Reputation Management", "Invoice Reminders", "5 Facebook Ads"],
    thumbnailGradient: ["#0EA5E9", "#06B6D4"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "26",
    name: "Business Coaching Snapshot",
    slug: "coaching",
    industry: "Coaching",
    category: "Professional Services",
    description: "Coaching CRM with optimized websites, sales funnels, AI chat bot, support ticket system, and lead magnet workflows.",
    longDescription: "Built for life coaches, business coaches, and consultants looking to scale their practice. Includes two fully optimized coaching websites, five sales funnels, four automated pipelines, four database reactivation campaigns, 52-week SMS and email campaigns, birthday campaign, incoming lead notifications with nurture, appointment workflows, support ticket workflows, lead magnets, an AI chat bot, reputation management, custom values, tags, forms, surveys, and 13 beautifully designed holiday emails.",
    price: 497,
    features: [
      "2 Fully Optimized Coaching Websites",
      "5 Fully Optimized Sales Funnels",
      "4 Automated Pipelines",
      "4 Database Reactivation Campaigns",
      "52-Week SMS/Email Campaigns",
      "Birthday Campaign",
      "Incoming Lead Notifications + Nurture",
      "Appointment Workflows",
      "Support Ticket Workflows",
      "Lead Magnets",
      "AI Chat Bot",
      "Reputation Management",
      "Custom Values, Tags, Forms & Surveys",
      "13 Beautifully Designed Holiday Emails",
    ],
    includes: ["2 Websites", "5 Funnels", "4 Pipelines", "4 DB Reactivation Campaigns", "52 SMS Campaigns", "52 Email Campaigns", "AI Chat Bot"],
    thumbnailGradient: ["#8B5CF6", "#A855F7"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
  {
    id: "27",
    name: "Mortgage Snapshot",
    slug: "mortgage",
    industry: "Mortgage",
    category: "Insurance & Finance",
    description: "Mortgage broker CRM with 13 sales funnels, power dialer, AI chat bot, and nurture campaigns for loan officers.",
    longDescription: "Built for mortgage brokers and loan officers looking to automate their pipeline. Includes fully optimized websites, thirteen fully optimized sales funnels, three automated pipelines, a power dialer, nurture campaigns, incoming lead notifications with nurture sequences, an AI chat bot, appointment workflows, custom values, tags, forms, surveys, and 13 beautifully designed holiday emails.",
    price: 497,
    features: [
      "Fully Optimized Websites",
      "13 Fully Optimized Sales Funnels",
      "3 Automated Pipelines",
      "Power Dialer",
      "Nurture Campaigns",
      "Incoming Lead Notifications + Nurture",
      "AI Chat Bot",
      "Appointment Workflows",
      "Custom Values, Tags, Forms & Surveys",
      "13 Beautifully Designed Holiday Emails",
    ],
    includes: ["Websites", "13 Funnels", "3 Pipelines", "Power Dialer", "AI Chat Bot", "Nurture Campaigns", "Holiday Emails"],
    thumbnailGradient: ["#059669", "#10B981"],
    ghlShareLink: "https://app.gohighlevel.com/snapshot/share/PLACEHOLDER",
  },
];

export const FAQ_ITEMS: FAQItem[] = [
  {
    question: "What is a GoHighLevel snapshot?",
    answer: "A snapshot is a pre-built template that installs an entire CRM setup into your GoHighLevel sub-account with one click. It includes pipelines, automations, workflows, funnels, email templates, websites, and more — all configured and ready to use for a specific industry.",
  },
  {
    question: "How do I install a snapshot?",
    answer: "After purchasing, you'll receive a GHL snapshot share link. Simply click the link, choose which sub-account to install it into, and everything will be imported automatically. The entire process takes under 5 minutes.",
  },
  {
    question: "Do I need a GoHighLevel account?",
    answer: "Yes, you need an active GoHighLevel account (Agency or SaaS plan) to install snapshots. Each snapshot is installed into a sub-account within your GHL dashboard.",
  },
  {
    question: "Can I customize the snapshot after installing?",
    answer: "Absolutely. Every element of the snapshot — pipelines, automations, funnels, emails, websites, and workflows — is fully editable. The snapshot gives you a professional starting point that you can customize to match your brand and specific business needs.",
  },
  {
    question: "Will installing a snapshot overwrite my existing setup?",
    answer: "No. Snapshots are additive — they add new elements to your sub-account without removing or overwriting anything that's already there. We recommend installing into a fresh sub-account for the cleanest setup.",
  },
  {
    question: "Can I resell the snapshots to other GHL users?",
    answer: "You are not permitted to sell the snapshots to other GHL users for them to use on their account. However, you are allowed to sell the services and digital products built from the snapshot to unlimited end clients.",
  },
  {
    question: "Do you offer refunds?",
    answer: "Due to the digital and instantly-delivered nature of snapshots, we are not able to offer refunds once a snapshot has been accessed. However, if you have any issues with installation or setup, our team is here to help.",
  },
  {
    question: "Does the price include future updates?",
    answer: "Yes! Each snapshot purchase includes all future updates at no additional cost. You'll always have access to the latest version of your snapshot.",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    quote: "Saved me at least 40 hours of setup time. The automations alone were worth every penny — I just had to swap in my branding and I was live.",
    name: "Marcus T.",
    title: "Agency Owner",
    industry: "Marketing Agency",
  },
  {
    quote: "My HVAC client was up and running in under an hour. The pipelines and follow-up sequences are exactly what a service business needs. Highly recommend.",
    name: "Sarah K.",
    title: "GHL Consultant",
    industry: "HVAC",
  },
  {
    quote: "I've bought snapshots from other providers before. These are on another level — the automations actually make sense, and the funnels convert out of the box.",
    name: "David R.",
    title: "SaaS Agency Owner",
    industry: "SaaS Agency",
  },
];

export const STATS: Stat[] = [
  { value: "27+", label: "Industry Snapshots" },
  { value: "500+", label: "Agencies Served" },
  { value: "15+", label: "Industries Covered" },
  { value: "<5min", label: "Average Install Time" },
];

export const CATEGORIES = [
  "All",
  "Home Services",
  "Health & Wellness",
  "Professional Services",
  "Agency",
  "Local Business",
  "Insurance & Finance",
] as const;
